HRMSmvc/Areas/Admin/Controllers/DashboardController.cs
using Domain.DTO;
using Domain.Models;
using HRMSmvc.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace HRMSmvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : BaseController
    {
        private readonly HttpClient client;
        private readonly IConfiguration _configuration;
        public DashboardController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, ILogger<BaseController> logger)
       : base(configuration, httpContextAccessor, logger)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            var employee = await GetAsync<ApiResponse<List<UserDTO>>> ("/api/Employee/GetEmp");

            if (employee == null)
            {
                ModelState.AddModelError(string.Empty, "Error fetching employee data.");
                return View(new List<User>());
            }

            // Return the list of employees to the view
            return View(employee.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] User employee)
        {
            var response = await PostAsync<ApiResponse<UserDTO>>("/api/Employee/CreateEmp", employee, null);
            return Json(response);  // Always return JSON
        }


        [HttpGet]
        public async Task<IActionResult> CreateorEdit(string Id)
        {
            if (Id != null)
            {
                var response = await GetAsync<ApiResponse<User>>("/api/Employee/GetEmpbyID?id=" + Id);

                return View(response.Data);
            }
            else
            {
                var user = new User
                {
                    DOB = DateTime.Today,
                    JoiningDate = DateTime.Today,
                    Id = null // Ensure Id is not set
                };
                return View(user);

            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] User employee)
        {
            var response = await PostAsync<ApiResponse<UserDTO>>("/api/Employee/UpdateEmp", employee, null);

            return Json(response);  
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid Id)
        {
            var employee = await GetAsync<User>($"/api/Employee/GetEmpbyID?id={Id}");
            if (employee == null)
            {
                ModelState.AddModelError(string.Empty, "Employee not found.");
                return View("Index");
            }

            // Use the HttpClient instance to send a DELETE request
            var response = await client.DeleteAsync($"/api/Employee/DeleteEmp?id={Id}");
            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError(string.Empty, "Error deleting employee.");
                return View("Index");
            }

            return Json(new { success = true, message = "Employee deleted successfully." });
        }
    }
}

HRMSmvc/Areas/Admin/Controllers/PayrollController.cs
using Domain.DTO;
using Domain.Models;
using HRMSmvc.Controllers;
using HRMSmvc.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HRMSmvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class PayrollController : BaseController
    {
        private readonly HttpClient client;
        private readonly IConfiguration _configuration;
        public PayrollController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, ILogger<BaseController> logger)
       : base(configuration, httpContextAccessor, logger)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> ViewPayroll(string userId)
        {
            var response = await GetAsync<ApiResponse<UserPayrollDTO>>($"/api/Payroll/GetPayrollByEmpID?EmpId={userId}");
            if (response != null && response.success)
            {
                return View("PayrollList", response.Data);
            }
            return View("PayrollList", new UserPayrollDTO());
        }

        [HttpGet]

        public async Task<IActionResult> GeneratePayroll(string userId)
        {
            var user = new PayrollDTO
            {
                UserId = userId
            };

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> GeneratePayroll([FromForm] PayrollDTO payroll)
        {
           var response = await PostAsync<ApiResponse<PayrollDTO>>("/api/Payroll/CreatePayroll", payroll, null);
            return Json(response); 
        }
    }
}

HRMSmvc/Areas/Client/Controllers/PayrollController.cs
using Domain.DTO;
using Domain.Models;
using HRMSmvc.Controllers;
using HRMSmvc.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace HRMSmvc.Areas.Client.Controllers
{
    [Area("Client")]

    public class PayrollController : BaseController
    {
        private readonly HttpClient client;
        private readonly IConfiguration _configuration;
        public PayrollController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, ILogger<BaseController> logger)
       : base(configuration, httpContextAccessor, logger)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> MyPayroll()
        {
            var userId = User.UserId();
            var response = await GetAsync<ApiResponse<UserPayrollDTO>>($"/api/Payroll/GetPayrollByEmpID?EmpId={userId}");
            if (response != null && response.success)
            {
                return View("PayrollIndex", response.Data);
            }
            return View("PayrollIndex", new List<PayrollDTO>());
        }
    }
}

HRMSmvc/Areas/Admin/Views/Payroll/GeneratePayroll.cshtml
@using Domain.DTO
@model PayrollDTO
@{
    ViewData["Title"] = "Generate Payroll";
    Layout = "_Layout";

}

<div class="card">
    <div class="card-body">
        <h3 class="card-title">Generate Payroll</h3>


<form asp-action="GeneratePayroll" asp-controller="Payroll" asp-area="Admin" id="genpayrollForm" method="post">
    <input type="hidden" id ="userId" name="userId" value="@Model.UserId" />
            <div class="row mb-3 mt-3">
                <div class="col-6">
                    <label asp-for="Year"></label>
                    <input asp-for="Year" class="form-control" />
                    @* <span asp-validation-for="FirstName" class="text-danger"></span> *@
                </div>
                <div class="col-6">
                    <label asp-for="Month"></label>
                    <input asp-for="Month" class="form-control" />
                    @* <span asp-validation-for="Email" class="text-danger"></span> *@
                </div>
            </div>
            <div class="row mb-3 mt-3">
                <div class="col-4">
                    <label asp-for="BasicSalary"></label>
                    <input asp-for="BasicSalary" class="form-control" />
                    @* <span asp-validation-for="PhoneNumber" class="text-danger"></span> *@
                </div>
                <div class="col-4">
                    <label asp-for="Allowances"></label>
                    <input asp-for="Allowances" class="form-control" />
                    @* <span asp-validation-for="PhoneNumber" class="text-danger"></span> *@
                </div>
                <div class="col-4">
                    <label asp-for="Deductions"></label>
                    <input asp-for="Deductions" class="form-control" />
                    @* <span asp-validation-for="PhoneNumber" class="text-danger"></span> *@
                </div>
            </div>
        <div class="text-center">
        <button type="submit" class="btn btn-primary mt-3 mb-3">Generate</button>
        <a asp-controller="Dashboard" asp-action="Index" asp-area="Admin" class="btn btn-primary">Back</a>
    </div>
</form>
</<div>

</div>

@section Scripts {
    <script src="~/js/admin.js"></script>
    <script src="~/js/payroll.js"></script>

}

HRMSmvc/Areas/Admin/Views/Payroll/PayrollList.cshtml
@using Domain.DTO
@using Domain.Models
@model UserPayrollDTO //List<PayrollDetailsDTO>
@{
	int counter = 1;
	// Initialize a counter to 1
}
@{
	ViewData["Title"] = "View Payroll";
	Layout = "_Layout";

}



	<div class="card">
		<div class="card-body">
			<h3 class="card-title">List of Payrolls for @Model.Name</h3>
			<div class="card-body mb-3">
				<div class="row">
					<div class="col-md-5">
						<label for="year">Year:</label>
						<input type="text" id="year" name="year" class="form-control">
					</div>
					<div class="col-md-5">
						<label for="month">Month:</label>
						<input type="text" id="month" name="month" class="form-control">
					</div>
					<div class="col-md-2">
						<a href="/Admin/Payroll/GeneratePayroll?userId=@Model.userId" class="btn btn-sm btn-primary mt-4" id="generatepayBtn">
							<i class="fa-solid fa-plus"></i> Generate
						</a>
					</div>
					
				</div>
			</div>


		</div>
	</div>





	<div class="card">
		<div class="card-body p-5">
			
			<!-- Default Table -->
			<table class="table" id="PayrollTable">
				<thead>
					<tr>
						@* <th scope="col">ID</th> *@
						<th scope="col">S.N.</th>
						<th scope="col">Year</th>
						<th scope="col">Month</th>
						<th scope="col">Basic Salary</th>
						<th scope="col">Allowances</th>
						<th scope="col">Deductions</th>
						<th scope="col">Net Salary</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var row in Model.payrolls)
					{
						<tr>
							@* <td>@row.Id</td> *@
							<td>@counter</td>
							<td>@row.Year</td>
							<td>@row.Month</td>
							<td>@row.BasicSalary</td>
							<td>@row.Allowances</td>
							<td>@row.Deductions</td>
							<td>@row.NetSalary</td>

						</tr>
						counter++;
					}
				</tbody>
			</table>
		</div>
	</div>


@section Scripts {
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<script src="~/js/payroll.js"></script>
}