HRMSmvc/Areas/Admin/Controllers/LeaveController.cs
using Domain.DTO;
using Domain.Models;
using HRMSmvc.Controllers;
using HRMSmvc.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HRMSmvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class LeaveController : BaseController
    {
        private readonly HttpClient client;
        private readonly IConfiguration _configuration;
        public LeaveController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, ILogger<BaseController> logger)
       : base(configuration, httpContextAccessor, logger)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> ViewAllLeaves()
        {
            var leaves = await GetAsync<ApiResponse<List<LeaveDetailsDTO>>>("/api/Leave/GetLeave");
            if (leaves == null)
            {
                ModelState.AddModelError(string.Empty, "Error fetching leave data.");
                return View(new List<LeaveDetailsDTO>());
            }
            // Return the list of leaves to the view
            return View("Index",leaves.Data);
        }

        [HttpPost]
        public async Task<IActionResult> ApproveLeave(Guid leaveRequestId)
        {
            var response = await PostAsync<ApiResponse<LeaveRequestDTO>>($"/api/Leave/ApproveLeave?leaveRequestId={leaveRequestId}", null , null);
            if (response == null || !response.success)
            {
                ModelState.AddModelError(string.Empty, "Error approving leave request.");
            }
            return RedirectToAction("ViewAllLeaves");
        }

        [HttpPost]
        public async Task<IActionResult> RejectLeave(Guid leaveRequestId)
        {
            var response = await PostAsync<ApiResponse<LeaveRequestDTO>>($"/api/Leave/RejectLeave?leaveRequestId={leaveRequestId}", null , null);
            if (response == null || !response.success)
            {
                ModelState.AddModelError(string.Empty, "Error rejecting leave request.");
            }
            return RedirectToAction("ViewAllLeaves");
        }
    }
}

HRMSmvc/Areas/Client/Controllers/LeaveController.cs
using Domain.DTO;
using Domain.Models;
using HRMSmvc.Controllers;
using HRMSmvc.Extensions;
using HRMSmvc.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HRMSmvc.Areas.Client.Controllers
{
    [Area("Client")]
    public class LeaveController : BaseController
    {
        private readonly HttpClient client;
        private readonly IConfiguration _configuration;
        public LeaveController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, ILogger<BaseController> logger)
       : base(configuration, httpContextAccessor, logger)
        {
            _configuration = configuration;
        }

        [HttpPost]
        public async Task<IActionResult> LeaveApply(LeaveRequestViewModel leaveRequestVm)
        {
            var dto = new LeaveRequestDTO
            {
                Id = leaveRequestVm.Id,
                RequestedById = User.UserId(),
                AppliedOn = leaveRequestVm.AppliedOn,
                StartDate = leaveRequestVm.StartDate,
                EndDate = leaveRequestVm.EndDate,
                Reason = leaveRequestVm.Reason,
                Status = leaveRequestVm.Status,
                LeaveType = leaveRequestVm.LeaveType,
                Description = leaveRequestVm.Description
            };

            var response = await PostAsync<ApiResponse<LeaveRequestDTO>>("/api/Leave/CreateLeave", dto, null);
            return Json(response);
        }

        [HttpGet]
        public IActionResult LeaveApply()
        {

            var viewModel = new LeaveRequestViewModel
            {
                StartDate = DateOnly.FromDateTime(DateTime.Now), 
                EndDate = DateOnly.FromDateTime(DateTime.Now.AddDays(1)),
                // Populate LeaveTypes with enum values as SelectListItems
                LeaveTypes = Enum.GetValues(typeof(LeaveType))
                                .Cast<LeaveType>()
                                .Select(e => new SelectListItem
                                {
                                    Value = ((int)e).ToString(),
                                    Text = e.ToString()
                                })


            };

            return View(viewModel);
        }
        
        [HttpGet]
        public async Task<IActionResult> MyLeaves()
        {
            var userId = User.UserId();
            var response = await GetAsync<ApiResponse<List<LeaveRequestDTO>>>(
                $"/api/Leave/GetLeaveByEmpID?EmpId={userId}");
            if (response != null && response.success)
            {
                return View("LeaveIndex",response.Data);
            }
            return View("LeaveIndex",new List<LeaveRequestDTO>());
        }
    }
}

HRMSmvc/Areas/Client/Views/Leave/LeaveApply.cshtml
@using Domain.Models
@using HRMSmvc.ViewModel


@model LeaveRequestViewModel
@{
    ViewData["Title"] = "Create Leave";
    Layout = "_UserLayout";

}
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Apply Leave</h3>

<!-- Vertical Form -->
<form asp-action="LeaveApply" id="LeaveForm" asp-controller="Leave" asp-area="Client" method="post">
            <div class="row mb-3 mt-3">
                <div class="col-6">
                    <label asp-for="Reason"></label>
                    <input asp-for="Reason" class="form-control" />
                </div>
                <div class="col-6">
                    <label asp-for="LeaveType"></label>
                    <select class="form-control" asp-for="LeaveType" asp-items="Model.LeaveTypes"></select>
                </div>
            </div>
            <div class="row mb-3 mt-3">
                <div class="col-6">
                    <label asp-for="StartDate"></label>
                    <input asp-for="StartDate" class="form-control" id="StartDate" />
                </div>
                <div class="col-6">
                    <label asp-for="EndDate"></label>
                    <input asp-for="EndDate" class="form-control" id="EndDate" />
                </div>
            </div>
            <div class="col-12">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
            </div>
    
    <div class="text-center">
        <button type="submit" class="btn btn-primary mt-3 mb-3">Apply Leave</button>
    </div>
</form>
</div>
</div>

@section Scripts {
	<script src="~/js/leave.js"></script>
}

HRMSmvc/Areas/Client/Views/Leave/LeaveIndex.cshtml
@using Domain.DTO
@using Domain.Models
@model List<LeaveRequestDTO>
@{
	int counter = 1;
	// Initialize a counter to 1
}
@{
    ViewData["Title"] = "View Leave";
    Layout = "_UserLayout";

}
<div class="card">
	<div class="card-body">
		<h3 class="card-title">List of Leaves</h3>
	<!-- Default Table -->
	<table class="table">
		<thead>
			<tr>
				@* <th scope="col">ID</th> *@
				<th scope="col">S.N.</th>
				<th scope="col">StartDate</th>
				<th scope="col">EndDate</th>
				<th scope="col">Reason</th>
				<th scope="col">Description</th>
				<th scope="col">LeaveType</th>
				<th scope="col">Status</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var row in Model)
			{
				<tr>
					@* <td>@row.Id</td> *@
					<td>@counter</td>
					<td>@row.StartDate</td>
					<td>@row.EndDate</td>
					<td>@row.Reason</td>
					<td>@row.Description</td>
					<td>@row.LeaveType</td>
					<td>@row.Status</td>
					
				</tr>
				counter++;
			}
		</tbody>
	</table>
</div>
</div>
</div>
</div>


@section Scripts {
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<script src="~/js/leave.js"></script>
}